version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  test:
    parameters:
      java-version:
        type: string
    executor:
      name: maven/default
      tag: << parameters.java-version >>
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn clean test

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test: &test
          matrix:
            parameters:
              java-version:
                - "8.0"
                - "11.0"
                - "13.0"
  build:
    jobs:
      - test:
          <<: *test
          filters:
            tags:
              only: /.*/
